version: '3'
services:
  client:
    image: node:16
    container_name: highrollers_fe
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./client/client
        target: /code-fe
    working_dir: /code-fe
    command: bash -c "npm install && npm run dev"
    depends_on:
      - server

  server:
    image: node:18
    container_name: highrollers_be
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./server/server
        target: /code-be
    working_dir: /code-be
    command: bash -c "npm install && npm run dev" 